version: "3.8"

services:
  unzip-bot:
    build: .
    restart: unless-stopped
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      BOT_TOKEN: ${BOT_TOKEN}
      CHANNEL_ID: ${CHANNEL_ID}
    volumes:
      - bot-downloads:/app/downloads
      - bot-extracted:/app/extracted

volumes:
  bot-downloads:
  bot-extracted:
